version: '3.8'

services:
  user-db:
    image: postgres:14
    container_name: user-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    volumes:
      - user-db-data:/var/lib/postgresql/data

volumes:
  user-db-data:

